# Generated by Django 4.2.6 on 2023-10-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_bytes', models.TextField()),
            ],
        ),
    ]
